// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunbookPlatform.Api.Data;

#nullable disable

namespace RunbookPlatform.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615063309_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RunbookPlatform.Api.Domain.Runbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runbooks");
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.RunbookVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAtPublish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunbookId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunbookId", "Number")
                        .IsUnique();

                    b.ToTable("RunbookVersions");
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.RunbookVersionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunbookVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunbookVersionId");

                    b.ToTable("RunbookVersionSteps");
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunbookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunbookId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.RunbookVersion", b =>
                {
                    b.HasOne("RunbookPlatform.Api.Domain.Runbook", null)
                        .WithMany("Versions")
                        .HasForeignKey("RunbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.RunbookVersionStep", b =>
                {
                    b.HasOne("RunbookPlatform.Api.Domain.RunbookVersion", null)
                        .WithMany("Steps")
                        .HasForeignKey("RunbookVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.Step", b =>
                {
                    b.HasOne("RunbookPlatform.Api.Domain.Runbook", null)
                        .WithMany("Steps")
                        .HasForeignKey("RunbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.Runbook", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RunbookPlatform.Api.Domain.RunbookVersion", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
